spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: smart-weighing-shelf-system
    file:
      upload:
        borrow-photo-path: ${user.dir}/uploads
        borrow-photo-access: /uploads/
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
logging:
  config: classpath:log4j2-dev.yml
lock:
  simulation:
    mode: false   # true=模拟模式, false=真实硬件模式
face-detect-provider: Baidu
# 百度人脸配置
baidu-face-config:
  use-fixed-path: false # 是否使用固定目录模型
  fixed-path: D:\Baidu-Face-Resources # 固定目录
  group-id: "common" # 固定组名

# 百度人脸检测阈值配置
face-threshold-config:
  live-score-min: 0.3
  mouth-close-score-min: 0.8
  eye-close-max: 0.1
  blur-max: 0.2
  similarity: 80.0
  faceOcclusion: 0.6

